/* eslint-disable max-len */
import { type NextPage } from 'next'
import Head from 'next/head'

import UI from '~/components/UI'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mikhail&apos;s CV page</title>
        <meta name="description" content="Generated by create-t3-app and me" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-3xl font-extrabold tracking-tight text-white ">
            Mikhail&apos;s <span className="text-[hsl(280,100%,70%)]">Web</span> Page
          </h1>
          <UI />
        </div>
      </main>
    </>
  )
}

export default Home
